#!/bin/sh -e

./Configure \
    --prefix=/usr \
    --openssldir=/etc/ssl \
    --libdir=lib \
    no-unit-test \
    shared \
    linux-x86_64-clang

make depend
make
make DESTDIR="$1" install_sw install_ssldirs

cp -f update-certdata.sh "$1/etc/ssl"

(
    cd libretls

    ./configure \
        --prefix=/usr \
        --with-openssl="$1/usr"

    make
    make DESTDIR="$1" install
)
