#!/bin/sh -e

patch -p1 < fix-busybox-diff.patch

CC=cc CXX=c++ ./configure \
    --prefix=/usr \
    --enable-vp8 \
    --enable-vp9 \
    --enable-experimental \
    --enable-runtime-cpu-detect \
    --enable-shared \
    --enable-postproc \
    --enable-pic \
    --disable-tools \
    --disable-examples \
    --disable-docs \
    --disable-unit-tests \
    --disable-install-docs \
    --disable-install-srcs \
    --disable-install-bins \
    --as=nasm

gmake
gmake DESTDIR="$1" install
