#!/bin/sh
cat <<EOF
Due to Dylan's disappearance, Wyverkiss will change its submodule
to point to a new repo in:

https://github.com/kiss-community/repo-main.git

(at least until Dylan's return)

User intervention might be needed at this stage (and for once only) to
synchronise with the new repo:

$ git submodule sync --recursive

And then you can update with 'kiss u' as normal.

Our apologies for the inconvenience.
EOF
