#!/bin/sh
cat <<EOF
With Dylan back in KISS development and Wyverkiss' goal being in sync
with Dylan's KISS repo, Wyverkiss will change back its submodule to
point at

https://github.com/kisslinux/repo.git

User intervention will be needed at this stage (and for once only) to
synchronise with the new repo:

$ git submodule sync --recursive

And then you can update with 'kiss u' as normal.

Our apologies for the inconvenience.
EOF
