--- xcb-util-wm-0.4.1/ewmh/Makefile.in
+++ xcb-util-wm-0.4.1/ewmh/Makefile.in
@@ -729,10 +729,10 @@
 
 
 ewmh.c: ewmh.c.m4 atomlist.m4
-	$(AM_V_GEN)$(M4) -I$(srcdir) $< >$@
+	$(AM_V_GEN)$(M4) -I$(srcdir) ewmh.c.m4 >ewmh.c
 
 xcb_ewmh.h: xcb_ewmh.h.m4 atomlist.m4
-	$(AM_V_GEN)$(M4) -I$(srcdir) $< >$@
+	$(AM_V_GEN)$(M4) -I$(srcdir) xcb_ewmh.h.m4 >xcb_ewmh.h
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
