#!/bin/sh -e

# Remove libc header which conflicts with 7 or so Linux
# kernel headers. See: https://github.com/kisslinux/repo/issues/207
sed -i '/net\/if/d' \
    dom/media/webrtc/transport/third_party/nICEr/src/stun/addrs-netlink.c

patch -p1 < if_indextoname.patch
patch -p1 < no-gtk2.patch

# autoconf requires GNU m4.
(
    cd m4-1.4.18
    ./configure \
        --prefix="$PWD/../junk"

    make
    make install
)

export PATH=$PWD/junk/bin:$PATH

# Build autoconf 2.13 for Firefox's sole use.
# See: https://bugzilla.mozilla.org/show_bug.cgi?id=104642
(
    cd autoconf2.13

    ./configure \
        --prefix="$PWD/../junk" \
        --program-suffix=-2.13

    make
    make install
)

# Build yasm for Firefox's sole use.
# Firefox is the only package which needs it
# and upstream is kinda dead.
(
    cd yasm

    ./configure \
        --prefix="$PWD/../junk"

    make
    make install
)

mkdir -p build
cd build

# Override ccache.
export CC="${CC:-/usr/bin/cc}"
export CXX="${CXX:-/usr/bin/c++}"

export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/firefox"
export RUSTFLAGS="$RUSTFLAGS -Cdebuginfo=0"
export MOZ_DEBUG_FLAGS=-g0
export MOZ_NOSPAM=1
export CXXSTDLIB=c++

../configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --enable-official-branding \
    --enable-optimize="$CFLAGS -w" \
    --enable-install-strip \
    --enable-strip \
    --enable-rust-simd \
    --enable-application=browser \
    --enable-release \
    --enable-alsa \
    --without-system-nspr \
    --without-system-nss \
    --without-system-libvpx \
    --with-system-jpeg \
    --with-system-zlib \
    --with-system-png \
    --with-system-pixman \
    --with-system-ffi \
    --disable-profiling \
    --disable-accessibility \
    --disable-tests \
    --disable-system-extension-dirs \
    --disable-parental-controls \
    --disable-debug-symbols \
    --disable-callgrind \
    --disable-vtune \
    --disable-elf-hack \
    --disable-gold \
    --disable-jemalloc \
    --disable-pulseaudio \
    --disable-crashreporter \
    --disable-updater \
    --disable-dbus \
    --disable-eme \
    --disable-necko-wifi

gmake
gmake DESTDIR="$1" install

# Remove a lot of unneeded "stuff".
rm -rf "$1/usr/include"
rm -rf "$1/usr/lib/firefox-devel"
rm -rf "$1/usr/share/idl"
rm -rf "$1/usr/lib/firefox/gtk2"
rm -f  "$1/usr/lib/firefox/browser/features/fxmonitor@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/screenshots@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/webcompat-reporter@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/doh-rollout@mozilla.org.xpi"
