#!/bin/sh -e

make -B \
    prefix=/usr \
    CC="${CC:-cc} $CFLAGS $CXXFLAGS" \
    -f unix/Makefile generic

make -B \
    prefix="$1/usr" \
    MANDIR="$1/usr/share/man/man1" \
    -f unix/Makefile install
