#!/bin/sh -e

(cd unix; patch -p1 < ../Makefile.patch)

make \
    prefix=/usr \
    CC="${CC:-cc} $CFLAGS $CXXFLAGS" \
    -f unix/Makefile generic

make \
    prefix="$1/usr" \
    MANDIR="$1/usr/share/man/man1" \
    -f unix/Makefile install
