#!/bin/sh -e

cd bmake

sed -e 's/build) op_test/build) /' \
    -e 's/	op_test//' boot-strap > _
mv -f _ boot-strap
chmod +x boot-strap

# Yeah, I have no idea why bmake do this.
sed -e 's/-nostdinc//' mk/sys/Linux.mk > _
mv -f _ mk/sys/Linux.mk

export CFLAGS="$CFLAGS -static"
export LDFLAGS="$LDFLAGS -static"

./boot-strap --with-default-sys-path=/usr/share/mk op=build
INSTALL=install ./boot-strap --prefix=/usr --with-mksrc=/usr/share/mk --install-destdir="$1" op=install

rm -rf "$1/usr/share/man/cat1"
mkdir -p "$1/usr/share/man/man1"
cp bmake.1 "$1/usr/share/man/man1/bmake.1"
ln -s bmake "$1/usr/bin/make"
