#!/bin/sh -e

export DESTDIR="$1"

# Remove 'atk-bridge' dependency which removes the 'dbus' dependency.
sed '/atkbridge_dep/d;/atk-bridge-2.0/d' meson.build > _
mv -f _ meson.build
sed '/atkbridge_dep,/d' gtk/meson.build > _
mv -f _ gtk/meson.build

sed '/<atk-bridge.h>/d;/atk_bridge_adaptor_init/d' \
    gtk/a11y/gtkaccessibility.c > _
mv -f _ gtk/a11y/gtkaccessibility.c

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dx11_backend=false \
    -Dprint_backends=auto \
    -Dwayland_backend=true \
    -Dwin32_backend=false \
    -Dquartz_backend=false \
    -Dcolord=no \
    -Ddemos=false \
    -Dexamples=false \
    -Dtests=false \
    -Dinstalled_tests=false \
    -Dgtk_doc=false \
    -Dintrospection=false \
    . build

ninja -C build
ninja -C build install
# We don't compile with librsvg which leads to this
# utility solely causing compiler errors for some
# packages. It has no use at all.
rm -f  "$1/usr/bin/gtk-encode-symbolic-svg"
rm -rf "$1/usr/share/gettext"
