#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-fribidi.patch
patch -p1 < schemas.patch

# GTK+3 on Wayland requires gsettings-desktop-schemes
# for gsettings to work correctly. Install the bare
# minimum needed (currently one schema).
#
# This fixes cursor icon issues and console spam when
# running Firefox.
(
    cd schemas

    meson \
    --prefix=/usr \
    -Dintrospection=false \
    . build

    ninja -C build
    ninja -C build install
)

# Remove 'atk-bridge' dependency which removes the 'dbus' dependency.
sed '/atkbridge_dep/d;/atk-bridge-2.0/d' meson.build > _
mv -f _ meson.build
sed '/atkbridge_dep,/d' gtk/meson.build > _
mv -f _ gtk/meson.build

sed '/<atk-bridge.h>/d;/atk_bridge_adaptor_init/d' \
    gtk/a11y/gtkaccessibility.c > _
mv -f _ gtk/a11y/gtkaccessibility.c

# Remove fribidi dependency. TODO: Fix the sed mess if possible.
sed '/fribidi_dep/d;/fribidi_req  /d;s/fribidi_req//;s/fribidi//' meson.build > _
mv -f _ meson.build
sed '/fribidi_dep,/d' gtk/meson.build > _
mv -f _ gtk/meson.build
sed '/fribidi_dep,/d' gdk/meson.build > _
mv -f _ gdk/meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dx11_backend=false \
    -Dprint_backends=auto \
    -Dwayland_backend=true \
    -Dwin32_backend=false \
    -Dquartz_backend=false \
    -Dcolord=no \
    -Ddemos=false \
    -Dexamples=false \
    -Dtests=false \
    -Dinstalled_tests=false \
    -Dgtk_doc=false \
    -Dintrospection=false \
    . build

ninja -C build
ninja -C build install
# We don't compile with librsvg which leads to this
# utility solely causing compiler errors for some
# packages. It has no use at all.
rm -f  "$1/usr/bin/gtk-encode-symbolic-svg"
rm -rf "$1/usr/share/gettext"
