#!/bin/sh -e

make CC="${CC:-cc} -static"

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/man/man1"

cp -f pigz unpigz "$1/usr/bin"
cp -f pigz.1 "$1/usr/share/man/man1"

# gzip compatibility
ln -s pigz   "$1/usr/bin/gzip"
ln -s pigz   "$1/usr/bin/zcat"
ln -s unpigz "$1/usr/bin/gunzip"
ln -s pigz.1 "$1/usr/share/man/man1/gzip.1"
