#!/bin/sh -e

sed -i '/CC.*-o/{s/$(LDFLAGS)//; s/$/ $(LDFLAGS)/}' Makefile

make CC="${CC:-cc}" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS -lz"

install -Dm755 pigz   "$1/usr/bin/pigz"
install -Dm755 unpigz "$1/usr/bin/unpigz"
install -Dm644 pigz.1 "$1/usr/share/man/man1/pigz.1"

# gzip compatibility
ln -s pigz   "$1/usr/bin/gzip"
ln -s pigz   "$1/usr/bin/zcat"
ln -s unpigz "$1/usr/bin/gunzip"
ln -s pigz.1 "$1/usr/share/man/man1/gzip.1"
