#!/bin/sh -e

cat > netbsd-curses.patch <<EOF
--- mutt/mutt_curses.h
+++ mutt/mutt_curses.h
@@ -52,6 +52,10 @@
 # include <curses.h>
 #endif
 
+// #include <term.h> - can't include term.h, because it defines macro columns which clashes
+// with variable name used in mutt, so just define the prototype for tigetstr()
+char *tigetstr(const char *capname);
+
 #define MUTT_ENTER_C '\n'
 #define MUTT_ENTER_S "\n"
 
EOF

patch -p1 < netbsd-curses.patch

out=$PWD/out
mkdir -p out

(
    cd cyrus-sasl

    export LDFLAGS="$LDFLAGS -lssl -lcrypto"

    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --disable-shared \
        --sbindir=/usr/bin

    gmake
    gmake DESTDIR="$out" install
)

# Remove perl dependency.
sed 's/ doc contrib/ contrib/g' Makefile.in > _
mv -f _ Makefile.in

export LDFLAGS="$LDFLAGS -lterminfo"

./configure \
    ac_cv_search_sasl_encode64=-lsasl2 \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-doc \
    --disable-full-doc \
    --enable-pop \
    --enable-imap \
    --enable-smtp \
    --with-ssl \
    --with-sasl="$out/usr"

make
make install-exec

rm -f "$1/etc/mime.types"
