#!/bin/sh -e


./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus

make AM_MAKEFLAGS=
make AM_MAKEFLAGS= install

cp -f iwd_passphrase "$1/usr/bin"

# Install runit service.
mkdir -p "$1/etc/sv/eiwd"
cp -f  eiwd.run                  "$1/etc/sv/eiwd/run"
ln -sf /run/runit/supervise.eiwd "$1/etc/sv/eiwd/supervise"
