#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus

# AM_MAKEFLAGS must be emptied. Otherwise, it'll set --no-print-directory.
# bmake doesn't support it.
make AM_MAKEFLAGS=
make AM_MAKEFLAGS= DESTDIR="$1" install

# Install runit service.
install -Dm755 eiwd.run         "$1/etc/sv/eiwd/run"
ln -s /run/runit/supervise.eiwd "$1/etc/sv/eiwd/supervise"
