#!/bin/sh
cat <<EOF
NOTE: Make sure you set your \$TERM value to something like:
      TERM=linux
      or
      TERM=xterm-256color
      Since netbsd-curses doesn't support foot's terminfo db.

      You can put it into your .profile, or set it globally in
      /etc/profile.d
EOF
