#!/bin/sh

cat <<EOF
NOTE: This is a transitional package. It can be removed safely.

We decided to remove wyverkiss_path.sh, so you'll have to re-setup it
manually. See our installation instructions for more information.

Since KISS' move to submodule model as primary method, Wyverkiss as an
alternative rootfs will follow suit.

After updating this repo to the latest commit, please modify git config
of Wyverkiss repo by cd-ing to your Wyverkiss repo path and type:

$ git config submodule.repo.ignore all

Otherwise, for every update every single change would be considered
"dirty", and subsequent 'kiss u' will be much harder.
EOF
