#!/bin/sh -e

# This package mimics the download process of rust's 'x.py'
# bootstrap library to allow for the removal of the internet
# connection requirement per build.
# The bootstrap uses a custom-made rust lib, tailored specifically for
# Wyverkiss.
{
    cache_dir=build/cache/2020-02-27
    mkdir -p "$cache_dir"

    for tarball in *.tar.xz\?no-extract; do
        mv -f "$tarball" "$cache_dir/${tarball%%\?no-extract}"
    done
}

# Ugly hack since rust looks for its libs dynamically. But it'll do.
export LD_LIBRARY_PATH="$PWD/build/x86_64-unknown-linux-musl/stage0/lib:$LD_LIBRARY_PATH"

patch -p1 < llvm-clang.patch

cat > config.toml <<EOF
[llvm]
link-shared = true

[build]
build = "x86_64-unknown-linux-musl"
host = [ "x86_64-unknown-linux-musl" ]
target = [ "x86_64-unknown-linux-musl" ]
docs = false
extended = true
submodules = false
python = "python3"
locked-deps = true
vendor = true

[install]
prefix = "/usr"

[rust]
channel = "stable"
rpath = false
codegen-units = 1
debuginfo-level = 0
backtrace = false
jemalloc = false
codegen-tests = false
llvm-libunwind = true

[target.x86_64-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
crt-static = false
EOF

python3 ./x.py build -j "$(nproc)"
DESTDIR="$1" python3 ./x.py install
