#!/bin/sh -e

# This package mimics the download process of rust's 'x.py'
# bootstrap library to allow for the removal of the internet
# connection requirement per build.
{
    cache_dir=build/cache/2021-06-17
    mkdir -p "$cache_dir"

    for tarball in *.tar.xz\?no-extract; do
        mv -f "$tarball" "$cache_dir/${tarball%%\?no-extract}"
    done
}

# Set shared linking as the default.
for f in \
    compiler/rustc_target/src/spec/linux_musl_base.rs \
    vendor/rustc-ap-rustc_target/src/spec/linux_musl_base.rs
do
    sed 's/\(crt_static_default = \)true/\1false/' "$f" > _
    mv -f _ "$f"
done

# Ignore checksums of files modified above.
sed 's/\("files":{\)[^}]*/\1/' \
    vendor/rustc-ap-rustc_target/.cargo-checksum.json > _
mv -f _ vendor/rustc-ap-rustc_target/.cargo-checksum.json

cat > config.toml <<EOF
[build]
build           = "x86_64-unknown-linux-musl"
host            = [ "x86_64-unknown-linux-musl" ]
target          = [ "x86_64-unknown-linux-musl" ]
docs            = false
compiler-docs   = false
extended        = true
submodules      = false
python          = "python3"
locked-deps     = true
vendor          = true
tools           = ["cargo", "rls", "clippy", "rustfmt", "analysis", "src", "rust-demangler"]
sanitizers      = false
profiler        = false
full-bootstrap  = false

[install]
prefix = "/usr"

[rust]
channel         = "stable"
rpath           = false
codegen-units   = 1
debuginfo-level = 0
backtrace       = false
jemalloc        = false
codegen-tests   = false
llvm-libunwind  = "system"

[target.x86_64-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
crt-static  = false
EOF

# What a disgusting hack. I really hope someone can find a better way.
# Otherwise I'll probably submit this to Dylan.
"$CC" -shared -o build/libgcc_s.so.1 -Wl,--allow-multiple-definition \
    -Wl,--whole-archive "$($CC -print-libgcc-file-name)" -lunwind
cat > build/libgcc_s.so <<EOF
INPUT(-lunwind)
EOF
export LD_LIBRARY_PATH="$PWD/build:$LD_LIBRARY_PATH"
export LIBRARY_PATH="$PWD/build:$LIBRARY_PATH"

python3 ./x.py build -j "$(nproc)"
DESTDIR="$1" python3 ./x.py install

rm -rf "$1/usr/lib/rustlib/src/" \
       "$1/usr/share/doc" \
       "$1/usr/share/zsh" \
       "$1/usr/lib/rustlib/uninstall.sh"
