#!/bin/sh -e

sed -i 's/ | \$(FLEX)$//' doc/Makefile.in

./configure \
    --prefix=/usr \
    ac_cv_func_malloc_0_nonnull=yes \
    ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR="$1" install

ln -s flex "$1/usr/bin/lex"
