#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-static \
    --enable-shared \
    ac_cv_func_malloc_0_nonnull=yes \
    ac_cv_func_realloc_0_nonnull=yes

gmake
gmake DESTDIR="$1" install
