#!/bin/sh -e

# This package mimics the download process of rust's 'x.py'
# bootstrap library to allow for the removal of the internet
# connection requirement per build.
# The bootstrap uses a custom-made rust lib, tailored specifically for
# Wyverkiss.
{
    cache_dir=build/cache/2020-08-27
    mkdir -p "$cache_dir"

    for tarball in *.tar.xz\?no-extract; do
        mv -f "$tarball" "$cache_dir/${tarball%%\?no-extract}"
    done
}

patch -p1 < llvm-clang.patch
patch -p1 < libressl-3.1.X.patch

sed -i 's/crt_static_default = true/crt_static_default = false/' src/librustc_target/spec/linux_musl_base.rs

# We modified vendored files here.
sed -i 's/\("files":{\)[^}]*/\1/' vendor/openssl-sys/.cargo-checksum.json

cat > config.toml <<EOF
[build]
build           = "x86_64-unknown-linux-musl"
host            = [ "x86_64-unknown-linux-musl" ]
target          = [ "x86_64-unknown-linux-musl" ]
docs            = false
compiler-docs   = false
extended        = true
submodules      = false
python          = "python3"
locked-deps     = true
vendor          = true
sanitizers      = false
profiler        = false
full-bootstrap  = false

[install]
prefix = "/usr"

[rust]
channel         = "stable"
rpath           = false
codegen-units   = 1
debuginfo-level = 0
backtrace       = false
jemalloc        = false
codegen-tests   = false
llvm-libunwind  = true

[target.x86_64-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
crt-static  = false
EOF

python3 ./x.py build -j "$(nproc)"
DESTDIR="$1" python3 ./x.py install

rm -rf "$1/usr/lib/rustlib/src/"
rm -f  "$1/usr/lib/rustlib/uninstall.sh"
