#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --with-xmldir=/etc/fonts \
    --enable-static \
    --disable-docs \
    --disable-nls

gmake
gmake DESTDIR="$1" install
