#!/bin/sh -e

# Avoid repeating ourselves.
mk() {
    gmake \
        libdir=/usr/lib/ \
        bindir=/usr/bin/ \
        mandir=/usr/share/man/ \
        includedir=/usr/include/ \
        "$@"
}

mk CC="${CC:-cc}"
mk DESTDIR="$1" install
