#!/bin/sh -e

export DESTDIR="$1"

sed -i "/subdir('tests')/d"    meson.build
sed -i "/subdir('examples')/d" meson.build

# For some reason, clang refuses to compile with G_GNUC_FALLTHROUGH
# (I *think* this should've existed in glib, but for now this should do.)
sed -i "s/G_GNUC_FALLTHROUGH/__attribute__((fallthrough));/" pango/break.c
sed -i "s/G_GNUC_FALLTHROUGH/__attribute__((fallthrough));/" pango/pango-renderer.c

meson \
    --prefix=/usr \
    -Dgir=false \
    -Dgtk_doc=false \
    -Dintrospection=false \
    -Dinstalled_tests=false \
    . build

ninja -C build
ninja -C build install
