#!/bin/sh -e

# Fix a python3 incompatibility.
sed -i 's|/ (8|// (8|' tools/gyp/pylib/gyp/generator/ninja.py

patch -p1 < no-gcc.patch

CC=cc CXX=c++ ./configure \
    --prefix=/usr \
    --shared-zlib \
    --without-intl \
    --without-etw \
    --without-dtrace \
    --without-report \
    --without-node-snapshot \
    --without-node-code-cache \
    --ninja

ninja -C out/Release
tools/install.py install "$1" /usr

# Remove unneeded headers.
rm -rf "$1/usr/include/node/openssl"
