#!/bin/sh -e

# Fix python3.
sed -i 's|(3, 8)|(3, 9), (3, 8)|g' configure

cat > no-gcc.patch <<EOF
--- node-v13.9.0/node.gyp
+++ node-v13.9.0/node.gyp
@@ -301,9 +301,6 @@
           '-Wl,-bnoerrmsg',
         ],
       }],
-      ['OS == "linux" and llvm_version != "0.0"', {
-        'libraries': ['-latomic'],
-      }],
     ],
   },
 
EOF

patch -p1 < no-gcc.patch

CC=cc CXX=c++ ./configure \
    --prefix=/usr \
    --shared-zlib \
    --without-intl \
    --without-etw \
    --without-dtrace \
    --without-report \
    --without-node-snapshot \
    --without-node-code-cache \
    --ninja

ninja -C out/Release
tools/install.py install "$1" /usr

# Remove unneeded files.
rm -rf "$1/usr/include/node/openssl"
rm -rf "$1/usr/lib/node_modules/npm/scripts"
rm -f  "$1/usr/lib/node_modules/npm/configure"
