#!/bin/sh -e

# Clang doesn't understand -Wtrampolines, -Wimplicit-fallthrough=5
sed -e 's/-Wtrampolines//g' -e 's/=5//g' lib/Makefile.in > _
mv -f _ lib/Makefile.in
sed -e 's/-Wtrampolines//g' -e 's/=5//g' libelf/Makefile.in > _
mv -f _ libelf/Makefile.in

# Build sometimes forces -Werror.
export CFLAGS="$CFLAGS -Wno-error"

# Disable configure error for missing argp, fts, and obstack
sed 's/as_fn_error.*\(argp\|fts\|obstack\)/: "/g' configure > _
mv -f _ configure

# Don't compile two unrelated C files which require argp.
sed 's/color.*printversion../#/g' lib/Makefile.in > _
mv -f _ lib/Makefile.in

sh ./configure \
    --prefix=/usr \
    --disable-symbol-versioning \
    --disable-debuginfod \
    --disable-nls \
    ac_cv_c99=yes

# Skip the default make target and build only what we need.
gmake -C lib
gmake -C libelf
gmake -C libelf DESTDIR="$1" install

mkdir -p "$1/usr/lib/pkgconfig"
cp -f config/libelf.pc "$1/usr/lib/pkgconfig/libelf.pc"
