#!/bin/sh -e

gmake HOSTCC="${CC:-cc}" headers

# The headers require rsync for installation, this command
# simply does the equivalent using find.
find usr/include -name \*.h -type f | while read -r file; do
    mkdir -p "$1/${file%/*}"
    cp -f "$file" "$1/$file"
done
