#!/bin/sh -e

patch -p1 < portability.patch

CC=cc CXX=c++ ./configure \
    --prefix=/usr \
    --disable-swscale \
    --enable-static \
    --enable-pic \
    --enable-shared

gmake
gmake DESTDIR="$1" install
