#!/bin/sh -e
# shellcheck disable=2016

# Fix alsamixer for netbsd-curses
sed -e 's/ MIN_MENU_COMMAND/REQ_LEFT_ITEM/' \
    -e 's/ MAX_MENU_COMMAND/REQ_PREV_MATCH/' \
    alsamixer/bindings.h > _
mv -f _ alsamixer/bindings.h

# Makefile fix
sed '/\$(edit)\|\.\(service\|rules\)/d' alsactl/Makefile.in > _
sed '/\$(edit)\|\.\(service\|rules\)/d' alsaucm/Makefile.in > __
mv -f _  alsactl/Makefile.in
mv -f __ alsaucm/Makefile.in

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --with-udev-rules-dir=/usr/lib/udev/rules.d \
    --disable-alsaconf \
    --disable-bat \
    --disable-xmlto \
    --disable-nls

make
make DESTDIR="$1" install
