#!/bin/sh -e
# shellcheck disable=2016

# Fix a missing include
sed '/<syslog.h>/a #include <limits.h>' alsactl/utils.c > _
mv -f _ alsactl/utils.c

# Makefile fix
sed '/\$(edit)\|\.\(service\|rules\)/d' alsactl/Makefile.in > _
sed '/\$(edit)\|\.\(service\|rules\)/d' alsaucm/Makefile.in > __
mv -f _  alsactl/Makefile.in
mv -f __ alsaucm/Makefile.in

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --with-udev-rules-dir=/usr/lib/udev/rules.d \
    --disable-alsaconf \
    --disable-alsamixer \
    --disable-bat \
    --disable-xmlto \
    --disable-nls

make
make DESTDIR="$1" install
