#!/bin/sh -e

# Fix a missing include
sed -i '/<syslog.h>/a #include <linux/limits.h>' alsactl/utils.c

# Makefile fix
sed -i '/\$(edit)\|\.\(service\|rules\)/d' alsactl/Makefile.in
sed -i '/\$(edit)\|\.\(service\|rules\)/d' alsaucm/Makefile.in

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --with-udev-rules-dir=/usr/lib/udev/rules.d \
    --disable-alsaconf \
    --disable-alsamixer \
    --disable-bat \
    --disable-xmlto \
    --disable-nls

make
make DESTDIR="$1" install
